import { nanoid } from "nanoid";
let gen = nanoid;
const themes = {
    light: "light",
    dark: "dark",
    cupcake: "cupcake",
    bumblebee: "bumblebee",
    emerald: "emerald",
    corporate: "corporate",
    synthwave: "synthwave",
    retro: "retro",
    dim: "dim",
    nord: "nord",
    night: "night",
    abyss: "abyss",

    cyberpunk: "cyberpunk",
    valentine: "valentine",
    halloween: "halloween",
    garden: "garden",
    forest: "forest",
    aqua: "aqua",
    lofi: "lofi",
    pastel: "pastel",
    fantasy: "fantasy",
    wireframe: "wireframe",
    black: "black",
    luxury: "luxury",
    dracula: "dracula",
    cmyk: "cmyk",
    autumn: "autumn",
    business: "business",
    acid: "acid",
    lemonade: "lemonade",
    coffee: "coffee",
    winter: "winter",
    sunset: "sunset",
    caramellatte: "caramellatte",
    silk: "silk",
};
export { gen,themes};
